---
- name: Install node and npm
  vars_files:
    - deploy-vars
  hosts: "{{host}}"
  tasks:
    - name: Update apt repo and cache
      ansible.builtin.apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    - name: Install nodejs and npm
      ansible.builtin.apt: 
        pkg:
          - nodejs
          - npm

- name: Create a linux user for deployment 
  vars_files:
    - deploy-vars
  hosts: "{{host}}"
  tasks:
    - name: Add the user with a primary group of 'admin'
      ansible.builtin.user:
        name: "{{linux_name}}"
        comment: Node User
        uid: 1040
        group: admin

- name: deploy nodejs app
  vars_files:
    - deploy-vars
  hosts: "{{host}}"
  become: True
  become_user: "{{linux_name}}"
  tasks:
    - name: unpack the node file
      ansible.builtin.unarchive:
        src: "{{location}}/nodejs-app-{{version}}.tgz"
        dest: "{{user_home_dir}}"
    - name: Install dependencies
      community.general.npm:
        path: "{{user_home_dir}}/package"
    - name: Start the application
      ansible.builtin.command: 
        chdir: "{{user_home_dir}}/package/app"
        cmd: node server
      async: 1000
      poll: 0  
    - name: Ensure app is running
      ansible.builtin.shell: ps aux | grep node
      register: app_status
    - ansible.builtin.debug: msg={{app_status.stdout_lines}}


  