---
- name: Install python3, docker, docker-compose
  hosts: aws_ec2
  become: yes
  # become_user : root
  gather_facts: False # to fix issue with python3
  tasks:
    - name: Install python3 and docker
      vars:
        ansible_python_interpreter: /usr/bin/python
      ansible.builtin.yum: 
        name: 
          - python3
          - docker
        update_cache: yes
        state: present
    - name: Install Docker-compose
      ansible.builtin.get_url: 
        url: https://github.com/docker/compose/releases/download/1.27.4/docker-compose-Linux-{{lookup('pipe', 'uname -m')}}
        dest: /usr/local/bin/docker-compose
        mode: +x
    - name: Start docker daemon
      ansible.builtin.systemd:
        name: docker
        state: started
    # required for docker and docker compose
    - name: Install docker python module
      ansible.builtin.pip:
        name: 
          - docker
          - docker-compose

- name: create linux user and add to docker group
  hosts: aws_ec2
  become: yes
  vars_files:
    - rundocker-vars
  tasks: 
    - name: Create new linux user
      ansible.builtin.user:
        name: "{{linux_user}}"
        groups: "{{groups}}"


- name: Start docker containers
  hosts: aws_ec2
  # one way to pass password
  #vars_prompt:
    #- name: docker_password
      #prompt: Enter password for Docker registry

  # for simplicity, I use an exteranl file
  vars_files:
    - rundocker-vars
  tasks:
    - name: Copy docker compose
      ansible.builtin.copy:
        src: "{{docker_compose_file}}"
        dest: /home/{{linux_user}}/docker-compose.yaml
    - name: Docker login
      community.docker.docker_login: 
        registry_url: https://index.docker.io/v1/
        username: "{{docker_hub_user}}"
        password: "{{docker_hub_password}}"
    - name: Start container from compose
      community.docker.docker_compose: 
        project_src: /home/{{linux_user}}

