---
- name: install nginx web server
  hosts: webserver
  tasks:
    - name: install nginx
      apt:
        name: nginx
        state: latest
    - name: start nginx server
      service:
        name: nginx
        state: started
  