---
- name: Install java and net-tools
  hosts: 167.172.105.209
  tasks:
    - name: Update atp repo and cache
      ansible.builtin.apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    - name: Install Java 8
      ansible.builtin.apt: name=openjdk-8-jre-headless
    - name: Install net-tools
      ansible.builtin.apt: name=net-tools

- name: Download and unpack Nexus installer
  hosts: 167.172.105.209
  tasks: 
    - name: Check nexus folder stats
      ansible.builtin.stat:
        path: /opt/nexus
      register: stat_result  
    - name: Download Nexus
      ansible.builtin.get_url: 
        url: https://download.sonatype.com/nexus/3/latest-unix.tar.gz
        dest: /opt/
      register: download_result  
    - name: Untar nexus installer
      ansible.builtin.unarchive:
        src: "{{download_result.dest}}"
        dest: /opt/ 
        remote_src: yes   
      when: not stat_result.stat.exists    
    - name: Find nexus folder
      ansible.builtin.find: 
        paths: /opt
        pattern: "nexus-*"
        file_type: directory
      register: find_result
    - name: Rename nexus folder
      ansible.builtin.shell: mv {{find_result.files[0].path}} /opt/nexus
      when: not stat_result.stat.exists




